---
- name: Setup dns slave 1
  hosts: nsworker12
  remote_user: ansible
  become: yes
  tasks:
  - name: Add two IPv4 DNS server addresses
    nmcli:
      conn_name: enp0s3
      type: ethernet
      dns4:
      - 192.168.50.171
      - 192.168.50.170
      - 8.8.8.8
      dns4_search:
      - ziyotek2.local  
      state: present

  - name: Set a hostname
    hostname:
      name:  prdx-nsworker12.ziyotek2.local

  - name: restart network
    service:
      name: network
      state: restarted

  - name: Install packages
    yum:
      name:
        - bind
        - bind-utils
      state: latest

  - name: Configure dns slave1
    template:
      src: /home/ansible/project/dnsslave1conf
      dest: /etc/named.conf

  - name: Restart named
    service:
      name: named
      state: restarted
